version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - .:/app
    env_file:
      - .env/development/database
      - .env/development/app
    depends_on:
      - db
    environment:
      - RAILS_ENV=development
      - RAILS_SERVE_STATIC_FILES=true
      - DATABASE_HOST=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    command: bundle exec rails server -b 0.0.0.0

  db:
    image: postgres:13
    # volumes:
    #  - ./tmp/db:/var/lib/postgresql/data
    #  - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    env_file:
      - .env/development/database
    volumes:
      - db_data:/var/lib/postgresql/data
      - gem_cache:/usr/local/bundle

volumes:
  db_data: 
  gem_cache:

